// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvbY7GQkgmBrCbHh3ilq0hob7xLTlTfw',
    appId: '1:1043911493316:web:c5fe7db4c423ede207ab91',
    messagingSenderId: '1043911493316',
    projectId: 'machinetest-a885e',
    authDomain: 'machinetest-a885e.firebaseapp.com',
    storageBucket: 'machinetest-a885e.appspot.com',
    measurementId: 'G-H591ZLYF1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GGaq1tPMhYapTL7GA-n_vt13XI5UbnU',
    appId: '1:1043911493316:android:67cf9fce0c48134c07ab91',
    messagingSenderId: '1043911493316',
    projectId: 'machinetest-a885e',
    storageBucket: 'machinetest-a885e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGN3T3QqGHeLepWb4PvvPNoQlMJxoIrc',
    appId: '1:1043911493316:ios:f8df73ec651d0d7c07ab91',
    messagingSenderId: '1043911493316',
    projectId: 'machinetest-a885e',
    storageBucket: 'machinetest-a885e.appspot.com',
    iosClientId: '1043911493316-p5m6hepocv6bkks1sq2pr52otg4mbhh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.machinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuGN3T3QqGHeLepWb4PvvPNoQlMJxoIrc',
    appId: '1:1043911493316:ios:f8df73ec651d0d7c07ab91',
    messagingSenderId: '1043911493316',
    projectId: 'machinetest-a885e',
    storageBucket: 'machinetest-a885e.appspot.com',
    iosClientId: '1043911493316-p5m6hepocv6bkks1sq2pr52otg4mbhh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.machinetest',
  );
}
